### PR TITLE
Implement a pyproject.toml

### PR DESCRIPTION
**Pull request by casparvl**
This allows us to install with `pip install git+https://github.com/EESSI/test-suite.git`.

Alternatively, you can install a specific branch with `pip install git+https://github.com/EESSI/test-suite.git@branchname`.

This makes testing other people's features quite easy, as you don't need to clone their repo, checkout the right branch, etc.

### CODE REVIEW

**Comment by casparvl** [comment]
This is still work in progress, I'm trying to get it to also pull in `hpctestlib` from ReFrame upon installation, since that is not installed with `pip install reframe-hpc` at this time.

**Comment by terjekv** [comment]
Should we have a test suite for our tests? The toml-file suggests python3.6+ but we don’t actually have any way of actually validating that the tests work with those pythons.

**Comment by smoors** [comment]
> Should we have a test suite for our tests? The toml-file suggests python3.6+ but we don’t actually have any way of actually validating that the tests work with those pythons.

indeed, it doesn't work for me with python3.6.
for using *only*  `pyproject.toml`, you need a more recent setuptools than is supported by python3.6

i'll create a pr to this pr to add a corresponding setup.py + setup.cfg file

**Comment by boegel** [comment]
> Should we have a test suite for our tests? The toml-file suggests python3.6+ but we don’t actually have any way of actually validating that the tests work with those pythons.

We can definitely add a GitHub Actions workflow that check whether `pip install` works

**Comment by smoors** [comment]
one thing to note is that having this pip-installed does not work with recent ReFrame modules, because they add the `-S` option to the shebang:
```
#!/bin/python3 -S
```

this will also be a problem for the EESSI module of ReFrame because we decided to use `python -S` in the EESSI module

**Comment by smoors** [comment]
@casparvl see https://github.com/casparvl/eessi-test-suite/pull/1

**Review by smoors — APPROVED** [review]
lgtm

**Pull request merged**
