### PR TITLE
add scales 1_cpn_2_nodes and 1_cpn_4_nodes

### PR DESCRIPTION
**Pull request by smoors**

### CODE REVIEW

**Comment by smoors** [comment]
i ran a few gromacs tests with the new scales; everything seems to work fine, no changes needed in the hooks:

- 1_core_per_node_2_nodes cpu-only

```
#!/bin/bash
#SBATCH --job-name="rfm_GROMACS_EESSI_12c54a39"
#SBATCH --ntasks=2
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --output=rfm_job.out
#SBATCH --error=rfm_job.err
#SBATCH --time=0:30:0
#SBATCH --nodes=2
#SBATCH --partition=skylake,skylake_mpi
somecommandthatfails
module load GROMACS/2021.3-foss-2021a
export OMP_NUM_THREADS=1
curl -LJO https://github.com/victorusu/GROMACS_Benchmark_Suite/raw/1.0.0/HECBioSim/Crambin/benchmark.tpr
srun gmx_mpi mdrun -nb cpu -s benchmark.tpr -dlb yes -npme -1 -ntomp 1

```
- 1_core_per_node_4_cores cpu-only

```
#!/bin/bash
#SBATCH --job-name="rfm_GROMACS_EESSI_c4a6e54f"
#SBATCH --ntasks=4
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --output=rfm_job.out
#SBATCH --error=rfm_job.err
#SBATCH --time=0:30:0
#SBATCH --nodes=4
#SBATCH --partition=skylake,skylake_mpi
somecommandthatfails
module load GROMACS/2021.3-foss-2021a
export OMP_NUM_THREADS=1
curl -LJO https://github.com/victorusu/GROMACS_Benchmark_Suite/raw/1.0.0/HECBioSim/Crambin/benchmark.tpr
srun gmx_mpi mdrun -nb cpu -s benchmark.tpr -dlb yes -npme -1 -ntomp 1

```

- 1_core_per_node_4_cores gpu

```
#!/bin/bash
#SBATCH --job-name="rfm_GROMACS_EESSI_271aca6c"
#SBATCH --ntasks=4
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --output=rfm_job.out
#SBATCH --error=rfm_job.err
#SBATCH --time=0:30:0
#SBATCH --partition=ampere_gpu
#SBATCH --gpus-per-node=1
module load GROMACS/2021.3-foss-2021a-CUDA-11.3.1
export OMP_NUM_THREADS=1
curl -LJO https://github.com/victorusu/GROMACS_Benchmark_Suite/raw/1.0.0/HECBioSim/Crambin/benchmark.tpr
srun gmx_mpi mdrun -nb gpu -s benchmark.tpr -dlb yes -npme -1 -ntomp 1

```

**Comment by boegel** [comment]
The benefit of `1_core_per_node_2_nodes` is that it's crystal clear, but it is looooooong.

Would `cpn` make sense, so `1_cpn_2_nodes`?
Or maybe both if we think that `cpn` may be too cryptic for some, with `1_cpn_2_nodes` as alias for `1_core_per_node_2_nodes`?

**Comment by smoors** [comment]
`1_cpn_2_nodes` sounds good to me, and easy enough to remember once you know it.
that reminds me that we should add the new scales to the docs as well.

**Comment by smoors** [comment]
hm, adding aliases like this is annoying when filtering a subset of scales.
the alternative would be to use something else than strings for the keys, but i think it's not worth it,
so i'll just remove the aliases and keep the `_cpn_` strings

**Review by satishskamath — APPROVED** [review]
Tested this on Snellius and it works.

**Pull request merged**
