### PR TITLE
Stage lammps and cp2k data using fixture

### PR DESCRIPTION
**Pull request by casparvl**
Closes https://github.com/EESSI/test-suite/issues/201

### CODE REVIEW

**Comment by smoors** [comment]
actually, for CP2K we don't need a fixture at all.
the `src` directory is automatically staged by reframe, so the only thing we have to do is rename the `input` directory to `src`, remove `prerun_cmds`, and fix the executable_opts.

i'll make a PR for is.

**Comment by casparvl** [comment]
Ok, this PR should not be merged until we come up with a general strategy for deduplication of input files between test cases. Let's have the discussion here https://github.com/EESSI/test-suite/pull/207#pullrequestreview-2445128871

**Comment by casparvl** [comment]
Ok, I following up on the discussion in #207 , I think we should indeed explore an option to make this happen within `EESSI_Mixin`. However, to tackle the issues with currently running the daily tests, I'd like to get this PR merged as a bug fix. Just like when implementing `EESSI_Mixin` itself, we can _later_ always adopt a solution provided by `EESSI_Mixin` and get rid of this logic in the specific tests.

**Comment by smoors** [comment]
for reference, this is the error i got with the original PR:
```
Traceback (most recent call last):
  File "/vscmnt/brussel_pixiu_data/_data_brussel/100/vsc10009/reframe/eessitestsuite/venv_refr4.6.2/lib64/python3.9/site-packages/reframe/frontend/loader.py", line 206, in load
_from_file
    util.import_module_from_file(filename, force, parent)
  File "/vscmnt/brussel_pixiu_data/_data_brussel/100/vsc10009/reframe/eessitestsuite/venv_refr4.6.2/lib64/python3.9/site-packages/reframe/utility/__init__.py", line 117, in imp
ort_module_from_file
    return _do_import_module_from_file(filename, module_name)
  File "/vscmnt/brussel_pixiu_data/_data_brussel/100/vsc10009/reframe/eessitestsuite/venv_refr4.6.2/lib64/python3.9/site-packages/reframe/utility/__init__.py", line 69, in _do_
import_module_from_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/vscmnt/brussel_pixiu_data/_data_brussel/100/vsc10009/reframe/eessitestsuite/test-suite/eessi/testsuite/tests/apps/cp2k/cp2k.py", line 10, in <module>
    from eessi.testsuite.tests.apps.cp2k.cp2k_staging.cp2k_stage_input import EESSI_CP2K_stage_input
  File "/data/brussel/100/vsc10009/reframe/eessitestsuite/test-suite/eessi/testsuite/tests/apps/cp2k/cp2k_staging/cp2k_stage_input.py", line 6, in <module>
    class EESSI_CP2K_stage_input(rfm.RunOnlyRegressionTest):
  File "/data/brussel/100/vsc10009/reframe/eessitestsuite/test-suite/eessi/testsuite/tests/apps/cp2k/cp2k_staging/cp2k_stage_input.py", line 22, in EESSI_CP2K_stage_input
    sanity_patterns = sn.all([
  File "/data/brussel/100/vsc10009/reframe/eessitestsuite/test-suite/eessi/testsuite/tests/apps/cp2k/cp2k_staging/cp2k_stage_input.py", line 23, in <listcomp>
    sn.assert_found('.*', input_file, msg % input_file) for input_file in input_file_list
NameError: name 'msg' is not defined
```

a good explanation for the error is here:
https://stackoverflow.com/a/13913933

**Review by smoors — APPROVED** [review]
lgtm

**Pull request merged**
