### PR TITLE
LAMMPS: relax TotEng check fot lj test on ARM

### PR DESCRIPTION
**Pull request by laraPPr**

### CODE REVIEW

**Comment by smoors** [comment]
are you sure it's ok to do this?
can you paste the energy values at steps 0 and 100 to see how it changes?

**Comment by laraPPr** [comment]
```
   Step          Temp          E_pair         E_mol          TotEng         Press

         0   1.44          -6.7733681      0             -4.6134356     -5.0197073

       100   0.76087792    -5.7635991      0             -4.6223179      0.18609556
```

**Comment by smoors** [comment]
so the initial energy is exactly the same, which suggests that the energy calculation is correct on ARM.
after 100 steps it diverges a bit, but that is to be expected for an MD simulation.

**Review by smoors — APPROVED** [review]
lgtm

**Pull request merged**
