### PR TITLE
fix pip install and github actions

### PR DESCRIPTION
**Pull request by smoors**
fixes https://github.com/EESSI/test-suite/issues/82

tested and works for
- python 3.6 setuptools 39.2.0
- python 3.10.4 setuptools 68.0.0

~i also moved the `eessi` dir under `src` as recommended, see https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#src-layout~

### CODE REVIEW

**Comment by boegel** [comment]
@smoors I'm not in favor of moving everything under `src`... Is there a strong need for that?

Also, we need to make sure we catch the problem being fixed here in CI, so we should update the GitHub Actions workflow first to reproduce the problem with an older setuptools version on top of Python 3.6?

**Comment by smoors** [comment]
> @smoors I'm not in favor of moving everything under `src`... Is there a strong need for that?
> 
> Also, we need to make sure we catch the problem being fixed here in CI, so we should update the GitHub Actions workflow first to reproduce the problem with an older setuptools version on top of Python 3.6?

i don't really see the problem with moving it under `src`, but i have no strong preference so i reverted it back, it actually makes the setup even simpler.

adding the older setuptools to GH actions is coming up, i first wanted to see if the current ones pass.

**Comment by smoors** [comment]
the last commit imports the pip_install GH action from https://github.com/EESSI/test-suite/pull/87,
which correctly failed, and is now successful for all versions.

**Review by boegel — APPROVED** [review]
lgtm, thanks a lot for figuring this out @smoors!

**Pull request merged**
