### PR TITLE
initialize EESSI environment via prepare command in configuration for VSC Hortense

### PR DESCRIPTION
**Pull request by laraPPr**
Add the prepare commands for EESSI to the config file of vsc_hortense.py

### CODE REVIEW

**Comment by laraPPr** [comment]
Should there also be a comment added to the file that specifies that --sytem should be used in the ReFrame commando

**Comment by smoors** [comment]
> Should there also be a comment added to the file that specifies that --sytem should be used in the ReFrame commando

that's a good idea indeed. maybe also add that the corresponding `cluster` module should be loaded first?

**Comment by laraPPr** [comment]
> I understand this change is made because @casparvl suggested it, but note that this does assume that the EESSI environment is also set up in the session where `reframe` is being run, otherwise ReFrame will only generate checks for the modules available on the system (not in EESSI, since those modules are not visible).
> 
> edit: We could probably verify that the EESSI environment was set up, by checking whether an environment variable like `$EESSI_PREFIX` is defined, and produce a meaningful error if it's not?

The assumption, that the EESSI environment is set, is now made in all config files except Hortense. vsc_hortense.py is the only one which does not have a  prepare command where the EESSI environment is set.

**Comment by boegel** [comment]
@laraPPr OK, then it definitely makes sense to make this consistent.

In the longer term (in a future PR), we may want an easy way to switch between using EESSI (default) and not using EESSI (when `$EESSI_TEST_SUITE_USE_EESSI` is set to `no` for example), and checking whether the EESSI environment is initialized when EESSI is used (and maybe also make sure no other modules can be picked up from `$MODULEPATH`?).

**Review by boegel — APPROVED** [review]

**Pull request merged**
